title: Bharath Anandaraj # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  SDET architect with 10+ years of experience in software development and testing.
  Specialized in test automation, performance testing, and CI/CD.
  Worked on various domains like banking, insurance, and e-commerce.
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 